name: Upload Python Package

on:
  workflow_dispatch:
    branch: master

permissions:
  contents: read

jobs:
  build:
    runs-on: pavan
    strategy: 
       max_parallel:4
    python_version: [3.7]
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
      with:
        user: pavan
        password: ${{ secrets.PYPI_API_TOKEN }}

